/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallaRegistrarse;

import conectarse.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import pantallaLogin.PantallaLogin;

/**
 *
 * @author Napster
 */
public class PantallaRegistrarse extends javax.swing.JFrame {

    /**
     * Creates new form PantallaRegistrarse
     */
    public PantallaRegistrarse() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbRegistrarTitulo = new javax.swing.JLabel();
        txtRegistrarApellido = new javax.swing.JTextField();
        txtRegistrarUsuario = new javax.swing.JTextField();
        txtRegistrarNombre = new javax.swing.JTextField();
        passRegistrarRepetirPassword = new javax.swing.JPasswordField();
        passRegistrarPassword = new javax.swing.JPasswordField();
        txtRegistrarEmail = new javax.swing.JTextField();
        txtRegistrarNumeroCell = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JToggleButton();
        btnRegresar = new javax.swing.JButton();
        lbRegistrarEmail = new javax.swing.JLabel();
        lbRegistrarUsuario = new javax.swing.JLabel();
        lbRegistrarPassword = new javax.swing.JLabel();
        lbRegistrarRepetirPassowrd = new javax.swing.JLabel();
        lbRegistrarNombre = new javax.swing.JLabel();
        lbRegistrarApellido = new javax.swing.JLabel();
        lbRegistrarNumeroCell = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRegistrarTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbRegistrarTitulo.setText("REGISTRAR UN NUEVO USUARIO");
        jPanel1.add(lbRegistrarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 390, 30));
        jPanel1.add(txtRegistrarApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 330, 40));

        txtRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 330, 40));
        jPanel1.add(txtRegistrarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 330, 40));
        jPanel1.add(passRegistrarRepetirPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 330, 40));
        jPanel1.add(passRegistrarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 330, 40));
        jPanel1.add(txtRegistrarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 330, 40));
        jPanel1.add(txtRegistrarNumeroCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 330, 40));

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 140, 50));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 130, 50));

        lbRegistrarEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRegistrarEmail.setText("Email:");
        jPanel1.add(lbRegistrarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 50, 40));

        lbRegistrarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRegistrarUsuario.setText("Usuario:");
        jPanel1.add(lbRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 60, 40));

        lbRegistrarPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRegistrarPassword.setText("Password:");
        jPanel1.add(lbRegistrarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 80, 40));

        lbRegistrarRepetirPassowrd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRegistrarRepetirPassowrd.setText("Repetir Password:");
        jPanel1.add(lbRegistrarRepetirPassowrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 40));

        lbRegistrarNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRegistrarNombre.setText("Nombre:");
        jPanel1.add(lbRegistrarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 70, 40));

        lbRegistrarApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRegistrarApellido.setText("Apellido:");
        jPanel1.add(lbRegistrarApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, 40));

        lbRegistrarNumeroCell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRegistrarNumeroCell.setText("Numero De Cell:");
        jPanel1.add(lbRegistrarNumeroCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String usuario = txtRegistrarUsuario.getText();
        String pass = (String.valueOf(passRegistrarPassword.getPassword()));
        String pass2 = (String.valueOf(passRegistrarRepetirPassword.getPassword()));
        String nombre = txtRegistrarNombre.getText();
        String apellido = txtRegistrarApellido.getText();
        String nun_Cell = txtRegistrarNumeroCell.getText();
        String correo = txtRegistrarEmail.getText();

        if (pass.equals(pass2)) {
            if (usuario.length() != 0) {
                if (nombre.length() != 0) {
                    if (apellido.length() != 0) {
                        if (nun_Cell.length() != 0) {
                            if (correo.length() != 0) {
                                if (pass.length() != 0 && pass2.length() != 0) {


                                try {
                                    Connection con;
                                    con = Conexion.getConnection();
                                    PreparedStatement preparaConsulta = con.prepareStatement("INSERT INTO Usuarios  (usuario, passwordUser, nombre, apellido, numeroCell, email) VALUES (?,?,?,?,?,?)");
                                    preparaConsulta.setString(1, usuario);
                                    preparaConsulta.setString(2, pass);
                                    preparaConsulta.setString(3, nombre);
                                    preparaConsulta.setString(4, apellido);
                                    preparaConsulta.setString(5, nun_Cell);
                                    preparaConsulta.setString(6, correo);

                                    preparaConsulta.execute();

                                    con.commit();
                                    con.close();

                                    JOptionPane.showMessageDialog(null, "El Usuario fue registrado con exito");
                                } catch (SQLException e) {
                                    JOptionPane.showMessageDialog(null, "El Usuario no esta dispobible, porfavor intente con otro");
                                }
                                
                                } else {
                                    JOptionPane.showMessageDialog(null, "INGRESE LAS PASSWORD");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Digite su correo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Digite su numero de telefonico");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Digite su apellido");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Digite su nombre");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Digite un nombre de usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Password No coinciden");
        
        }


    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrarUsuarioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        PantallaLogin formularioLogin = new PantallaLogin();
        formularioLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbRegistrarApellido;
    private javax.swing.JLabel lbRegistrarEmail;
    private javax.swing.JLabel lbRegistrarNombre;
    private javax.swing.JLabel lbRegistrarNumeroCell;
    private javax.swing.JLabel lbRegistrarPassword;
    private javax.swing.JLabel lbRegistrarRepetirPassowrd;
    private javax.swing.JLabel lbRegistrarTitulo;
    private javax.swing.JLabel lbRegistrarUsuario;
    private javax.swing.JPasswordField passRegistrarPassword;
    private javax.swing.JPasswordField passRegistrarRepetirPassword;
    private javax.swing.JTextField txtRegistrarApellido;
    private javax.swing.JTextField txtRegistrarEmail;
    private javax.swing.JTextField txtRegistrarNombre;
    private javax.swing.JTextField txtRegistrarNumeroCell;
    private javax.swing.JTextField txtRegistrarUsuario;
    // End of variables declaration//GEN-END:variables
}
