
package pantallaGestionProductos;

import conectarse.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pntallaPrincipal.PantallaPrincipal;


public class PantallaGestionDeProductos extends javax.swing.JFrame {


    int idProducto;
    int precio;
    int cantidad;

    public PantallaGestionDeProductos() {
        initComponents();
        CargarTabla();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbGestionProductosTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionProductosTabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtGestionProductosPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGestionProductosStock = new javax.swing.JTextField();
        btnGestionProductosModificar = new javax.swing.JButton();
        txtGestionProductosMarca = new javax.swing.JTextField();
        btnGestionProductosEliminar = new javax.swing.JButton();
        txtGestionProductosCategoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnGestionProductosRegresar = new javax.swing.JButton();
        btnGestionProductosGuardar = new javax.swing.JButton();
        txtGestionProductosID = new javax.swing.JTextField();
        txtGestionProductosNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbGestionProductosTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbGestionProductosTitulo.setText("GESTION DE PRODUCTOS PROYECTO FINAL");
        jPanel1.add(lbGestionProductosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PRECIO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 70, 40));

        tblGestionProductosTabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblGestionProductosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "MARCA", "CATEGORIA", "PRECIO", "STOCK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblGestionProductosTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGestionProductosTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGestionProductosTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 680, 260));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CATEGORIA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NOMBRE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 70, 40));
        jPanel1.add(txtGestionProductosPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 260, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("STOCK:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 60, 40));
        jPanel1.add(txtGestionProductosStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 260, 40));

        btnGestionProductosModificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGestionProductosModificar.setText("MODIFICAR");
        btnGestionProductosModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionProductosModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionProductosModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 170, 40));
        jPanel1.add(txtGestionProductosMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 220, 40));

        btnGestionProductosEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGestionProductosEliminar.setText("ELIMINAR");
        btnGestionProductosEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionProductosEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionProductosEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 170, 40));
        jPanel1.add(txtGestionProductosCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 220, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("MARCA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 60, 40));

        btnGestionProductosRegresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGestionProductosRegresar.setText("REGRESAR");
        btnGestionProductosRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionProductosRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionProductosRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 170, 40));

        btnGestionProductosGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGestionProductosGuardar.setText("GUARDAR");
        btnGestionProductosGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionProductosGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionProductosGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 170, 40));
        jPanel1.add(txtGestionProductosID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 0, 40));
        jPanel1.add(txtGestionProductosNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblGestionProductosTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGestionProductosTablaMouseClicked

        try {

            int fila = tblGestionProductosTabla.getSelectedRow();

            String usuario = String.valueOf(tblGestionProductosTabla.getValueAt(fila, 0));

            this.idProducto = Integer.parseInt(usuario);

            PreparedStatement prepararConsulta;
            ResultSet resultado;

            Connection con = Conexion.getConnection();
            prepararConsulta = con.prepareStatement("SELECT * FROM Productos WHERE idProducto = ?");
            prepararConsulta.setInt(1, idProducto);
            resultado = prepararConsulta.executeQuery();

            while (resultado.next()) {
                txtGestionProductosMarca.setText(resultado.getString("marcaProducto"));
                txtGestionProductosPrecio.setText(resultado.getString("precioProcto"));
                txtGestionProductosStock.setText(resultado.getString("stockProducto"));
                txtGestionProductosCategoria.setText(resultado.getString("categoriaProducto"));
                txtGestionProductosNombre.setText(resultado.getString("nombreProductos"));
                txtGestionProductosID.setText(resultado.getString("idProducto"));
            }
            con.commit();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_tblGestionProductosTablaMouseClicked

    private void btnGestionProductosModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProductosModificarActionPerformed
        String marca = txtGestionProductosMarca.getText();
        
        try {
            precio = Integer.parseInt(txtGestionProductosPrecio.getText());
            cantidad = Integer.parseInt(txtGestionProductosStock.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite un valor numerico");
        }
        
        String categoria = txtGestionProductosCategoria.getText();
        String nombre = txtGestionProductosNombre.getText();
        int idProductos = Integer.parseInt(txtGestionProductosID.getText());

        if (marca.length() != 0) {
            if (nombre.length() != 0) {
                if (categoria.length() != 0) {
                    try {
                        Connection conPrueva = Conexion.getConnection();
                        PreparedStatement prepararConsultaPrueva = conPrueva.prepareStatement("SELECT * FROM Productos  WHERE idProducto = ?");
                        prepararConsultaPrueva.setInt(1, idProductos);
                        ResultSet resultadoPrueva = null;
                        resultadoPrueva = prepararConsultaPrueva.executeQuery();
                        conPrueva.commit();

                        if (resultadoPrueva.next()) {
                            Connection con = Conexion.getConnection();
                            PreparedStatement preparaConsulta = con.prepareStatement("UPDATE Productos  SET nombreProductos = ?, marcaProducto = ?, categoriaProducto = ?, precioProcto = ?,  stockProducto = ? WHERE idProducto = ?");
                            preparaConsulta.setString(1, nombre);
                            preparaConsulta.setString(2, marca);
                            preparaConsulta.setString(3, categoria);
                            preparaConsulta.setInt(4, precio);
                            preparaConsulta.setInt(5, cantidad);
                            preparaConsulta.setInt(6, idProducto);

                            preparaConsulta.execute();
                            JOptionPane.showMessageDialog(null, "El Producto se ha actualizado");
                            con.commit();
                            con.close();
                            CargarTabla();

                        } else {
                            JOptionPane.showMessageDialog(null, "EL PRODUCTO QUE INTENTA ACTUALIZAR NO EXISTE");
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e.toString());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "DIGITE LA CATEGORIA DEL PRODUCTO");
                }
            } else {
                JOptionPane.showMessageDialog(null, "DIGITE NOMBRE DE PRODUCTO");
            }
        } else {
            JOptionPane.showMessageDialog(null, "DIGITE MARCA DE PRODUCTO");
        }
    }//GEN-LAST:event_btnGestionProductosModificarActionPerformed

    private void btnGestionProductosEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProductosEliminarActionPerformed

        int productoid = Integer.parseInt(txtGestionProductosID.getText());

        try {
            Connection conPrueva = Conexion.getConnection();
            PreparedStatement prepararConsultaPrueva = conPrueva.prepareStatement("SELECT * FROM Productos WHERE idProducto = ?");
            prepararConsultaPrueva.setInt(1, productoid);
            ResultSet resultadoPrueva = null;
            resultadoPrueva = prepararConsultaPrueva.executeQuery();
            conPrueva.commit();

            if (resultadoPrueva.next()) {
                Connection con = Conexion.getConnection();
                PreparedStatement preparaConsulta = con.prepareStatement("DELETE FROM Productos WHERE idProducto = ?");
                preparaConsulta.setInt(1, productoid);

                preparaConsulta.execute();
                JOptionPane.showMessageDialog(null, "EL PRODUCTO SE HA ELIMINADO");

                con.commit();
                con.close();
                CargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "EL PRODUCTO QUE INTENTA ELIMINAR NO EXISTE");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnGestionProductosEliminarActionPerformed

    private void btnGestionProductosRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProductosRegresarActionPerformed
        PantallaPrincipal formularioPantallaPrincipal = new PantallaPrincipal();
        formularioPantallaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestionProductosRegresarActionPerformed

    private void btnGestionProductosGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProductosGuardarActionPerformed
        String marca = txtGestionProductosMarca.getText();
        
        try {
            precio = Integer.parseInt(txtGestionProductosPrecio.getText());
            cantidad = Integer.parseInt(txtGestionProductosStock.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite un valor numerico");
        }
        
        String categoria = txtGestionProductosCategoria.getText();
        String nombre = txtGestionProductosNombre.getText();

        if (marca.length() != 0) {
            if (nombre.length() != 0) {
                if (categoria.length() != 0) {
                    try {
                        Connection con;
                        con = Conexion.getConnection();
                        PreparedStatement preparaConsulta = con.prepareStatement("INSERT INTO Productos  (nombreProductos, marcaProducto, categoriaProducto, precioProcto, stockProducto) VALUES (?,?,?,?,?)");
                        preparaConsulta.setString(1, nombre);
                        preparaConsulta.setString(2, marca);
                        preparaConsulta.setString(3, categoria);
                        preparaConsulta.setInt(4, precio);
                        preparaConsulta.setInt(5, cantidad);

                        preparaConsulta.execute();

                        con.commit();
                        con.close();
                        CargarTabla();
                        JOptionPane.showMessageDialog(null, "El Producto fue registrado exitosamente");
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "El Producto esta registrado" + e.toString());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Digite la categoria del Producto");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Digite Nombre del Producto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite Marca del Producto");
        }
    }//GEN-LAST:event_btnGestionProductosGuardarActionPerformed

    private void CargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblGestionProductosTabla.getModel();

        modeloTabla.setRowCount(0);

        PreparedStatement prepararConsulta;
        ResultSet resultado;

        ResultSetMetaData resultadoMetadata;

        int columnas;

        try {

            Connection con = Conexion.getConnection();
            prepararConsulta = con.prepareStatement("SELECT * FROM Productos");
            resultado = prepararConsulta.executeQuery();

            resultadoMetadata = resultado.getMetaData();

            columnas = resultadoMetadata.getColumnCount();

            while (resultado.next()) {

                Object[] filas = new Object[columnas];

                for (int i = 0; i < columnas; i++) {

                    filas[i] = resultado.getObject(i + 1);
                }

                modeloTabla.addRow(filas);
            }

            con.commit();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDeProductos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDeProductos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDeProductos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDeProductos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaGestionDeProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionProductosEliminar;
    private javax.swing.JButton btnGestionProductosGuardar;
    private javax.swing.JButton btnGestionProductosModificar;
    private javax.swing.JButton btnGestionProductosRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGestionProductosTitulo;
    private javax.swing.JTable tblGestionProductosTabla;
    private javax.swing.JTextField txtGestionProductosCategoria;
    private javax.swing.JTextField txtGestionProductosID;
    private javax.swing.JTextField txtGestionProductosMarca;
    private javax.swing.JTextField txtGestionProductosNombre;
    private javax.swing.JTextField txtGestionProductosPrecio;
    private javax.swing.JTextField txtGestionProductosStock;
    // End of variables declaration//GEN-END:variables
}
