/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallaGestionUsuarios;

import conectarse.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pntallaPrincipal.PantallaPrincipal;

/**
 *
 * @author Napster
 */
public class PantallaGestionDeUsuario extends javax.swing.JFrame {

    /**
     * Creates new form PantallaGestionDeUsuario
     */
    String user;

    public PantallaGestionDeUsuario() {
        initComponents();
        CargarTabla();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionUsuarioTabla = new javax.swing.JTable();
        lbGestionUsuarioTitulo = new javax.swing.JLabel();
        txtGestionUsuarioNumeroCell = new javax.swing.JTextField();
        passGestionUsuarioPass2 = new javax.swing.JPasswordField();
        passGestionUsuarioPass1 = new javax.swing.JPasswordField();
        txtGestionUsuarioUser = new javax.swing.JTextField();
        txtGestionUsuarioNombre = new javax.swing.JTextField();
        txtGestionUsuarioApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGestionUsuarioModificar = new javax.swing.JButton();
        btnGestionUsuarioGuardar = new javax.swing.JButton();
        btnGestionUsuarioRegresar = new javax.swing.JButton();
        btnGestionUsuarioEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtGestionUsuarioEmail1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblGestionUsuarioTabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblGestionUsuarioTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USUARIO", "PASSWORD", "NOMBRE", "APELLIDO", "NUMERO CELL", "EMAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblGestionUsuarioTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGestionUsuarioTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGestionUsuarioTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 680, 260));

        lbGestionUsuarioTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbGestionUsuarioTitulo.setText("GESTION DE USUARIOS PROYECTO FINAL");
        jPanel1.add(lbGestionUsuarioTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
        jPanel1.add(txtGestionUsuarioNumeroCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 220, 40));
        jPanel1.add(passGestionUsuarioPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 220, 40));
        jPanel1.add(passGestionUsuarioPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 220, 40));
        jPanel1.add(txtGestionUsuarioUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 220, 40));
        jPanel1.add(txtGestionUsuarioNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 260, 40));
        jPanel1.add(txtGestionUsuarioApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 260, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Numero Cell:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 100, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 70, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 70, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 70, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 80, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Repetir Pass:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, 40));

        btnGestionUsuarioModificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGestionUsuarioModificar.setText("MODIFICAR");
        btnGestionUsuarioModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuarioModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionUsuarioModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 170, 40));

        btnGestionUsuarioGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGestionUsuarioGuardar.setText("GUARDAR");
        btnGestionUsuarioGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuarioGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionUsuarioGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 170, 40));

        btnGestionUsuarioRegresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGestionUsuarioRegresar.setText("REGRESAR");
        btnGestionUsuarioRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuarioRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionUsuarioRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 170, 40));

        btnGestionUsuarioEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGestionUsuarioEliminar.setText("ELIMINAR");
        btnGestionUsuarioEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuarioEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionUsuarioEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 170, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Email:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 50, 40));
        jPanel1.add(txtGestionUsuarioEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionUsuarioModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuarioModificarActionPerformed
        String usuario = txtGestionUsuarioUser.getText();
        String pass = (String.valueOf(passGestionUsuarioPass1.getPassword()));
        String pass2 = (String.valueOf(passGestionUsuarioPass2.getPassword()));
        String nombre = txtGestionUsuarioNombre.getText();
        String apellido = txtGestionUsuarioApellido.getText();
        String nun_Cell = txtGestionUsuarioNumeroCell.getText();
        String correo = txtGestionUsuarioEmail1.getText();

        if (pass.equals(pass2)) {
            if (usuario.length() != 0) {
                if (nombre.length() != 0) {
                    if (apellido.length() != 0) {
                        if (nun_Cell.length() != 0) {
                            if (correo.length() != 0) {
                                if (pass.length() != 0 && pass2.length() != 0) {


                                try {
                                    Connection conPrueva = Conexion.getConnection();
                                    PreparedStatement prepararConsultaPrueva = conPrueva.prepareStatement("SELECT * FROM usuarios WHERE usuario = ?");
                                    prepararConsultaPrueva.setString(1, this.user);
                                    ResultSet resultadoPrueva = null;
                                    resultadoPrueva = prepararConsultaPrueva.executeQuery();
                                    conPrueva.commit();

                                    if (resultadoPrueva.next()) {
                                        Connection con = Conexion.getConnection();
                                        PreparedStatement preparaConsulta = con.prepareStatement("UPDATE usuarios SET usuario = ?, passwordUser = ?, nombre = ?, apellido = ?,  numeroCell = ?, email = ? WHERE usuario = ?");
                                        preparaConsulta.setString(1, usuario);
                                        preparaConsulta.setString(2, pass);
                                        preparaConsulta.setString(3, nombre);
                                        preparaConsulta.setString(4, apellido);
                                        preparaConsulta.setString(5, nun_Cell);
                                        preparaConsulta.setString(6, correo);
                                        preparaConsulta.setString(7, this.user);

                                        preparaConsulta.execute();
                                        JOptionPane.showMessageDialog(null, "USUARIO ACTUALIZADO");
                                        con.commit();
                                        con.close();
                                        CargarTabla();

                                    } else {
                                        JOptionPane.showMessageDialog(null, "EL USUARIO QUE INTENTA ACTUALIZAR NO EXISTE");
                                    }

                                } catch (SQLException e) {
                                    JOptionPane.showMessageDialog(null, e.toString());

                                }
                                
                                } else {
                                    JOptionPane.showMessageDialog(null, "INGRESE LOS PASSWORD");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Ingrese su correo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Ingrese su numero de telefono");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Ingrese su apellido");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese su nombre");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un nombre de usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Password No coinciden");
        }
    }//GEN-LAST:event_btnGestionUsuarioModificarActionPerformed

    private void btnGestionUsuarioGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuarioGuardarActionPerformed
        String usuario = txtGestionUsuarioUser.getText();
        String pass = (String.valueOf(passGestionUsuarioPass1.getPassword()));
        String pass2 = (String.valueOf(passGestionUsuarioPass2.getPassword()));
        String nombre = txtGestionUsuarioNombre.getText();
        String apellido = txtGestionUsuarioApellido.getText();
        String nun_Cell = txtGestionUsuarioNumeroCell.getText();
        String correo = txtGestionUsuarioEmail1.getText();

        if (pass.equals(pass2)) {
            if (usuario.length() != 0) {
                if (nombre.length() != 0) {
                    if (apellido.length() != 0) {
                        if (nun_Cell.length() != 0) {
                            if (correo.length() != 0) {
                                if (pass.length() != 0 && pass2.length() != 0) {


                                try {
                                    Connection con;
                                    con = Conexion.getConnection();
                                    PreparedStatement preparaConsulta = con.prepareStatement("INSERT INTO Usuarios  (usuario, passwordUser, nombre, apellido, numeroCell, email) VALUES (?,?,?,?,?,?)");
                                    preparaConsulta.setString(1, usuario);
                                    preparaConsulta.setString(2, pass);
                                    preparaConsulta.setString(3, nombre);
                                    preparaConsulta.setString(4, apellido);
                                    preparaConsulta.setString(5, nun_Cell);
                                    preparaConsulta.setString(6, correo);

                                    preparaConsulta.execute();

                                    con.commit();
                                    con.close();
                                    CargarTabla();
                                    JOptionPane.showMessageDialog(null, "EL USUARIO FUE REGISTRADO CON EXITO");
                                } catch (SQLException e) {
                                    JOptionPane.showMessageDialog(null, "EL USUARIO NO ESTA DISPONIBLE INTENTE CON OTRO");
                                }
                                
                                } else {
                                    JOptionPane.showMessageDialog(null, "INGRESE LAS PASSWORD");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Ingrese su correo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Ingrese su numero de telefono");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Ingrese su apellido");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese su nombre");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un nombre de usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Password No coinciden");
        }
    }//GEN-LAST:event_btnGestionUsuarioGuardarActionPerformed

    private void btnGestionUsuarioRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuarioRegresarActionPerformed
        PantallaPrincipal formularioPantallaPrincipal = new PantallaPrincipal();
        formularioPantallaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestionUsuarioRegresarActionPerformed

    private void btnGestionUsuarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuarioEliminarActionPerformed
        //Capturamos el usuario introducido en el txtField
        String usuario = txtGestionUsuarioUser.getText();
        
        try {
            //Probamos con un select a ver si existe
            Connection conPrueva = Conexion.getConnection();
            PreparedStatement prepararConsultaPrueva = conPrueva.prepareStatement("SELECT * FROM usuarios WHERE usuario = ?");
            prepararConsultaPrueva.setString(1, usuario);
            ResultSet resultadoPrueva = null;
            resultadoPrueva = prepararConsultaPrueva.executeQuery();
            conPrueva.commit();
            
            //Si existe pues procedemos a eliminarlo con un delet
            if (resultadoPrueva.next()) {
                Connection con = Conexion.getConnection();
                PreparedStatement preparaConsulta = con.prepareStatement("DELETE FROM usuarios WHERE usuario = ?");
                preparaConsulta.setString(1, usuario);

                preparaConsulta.execute();
                JOptionPane.showMessageDialog(null, "USUARIO ELIMINADO");
                
                //Recordar el commit y el close
                con.commit();
                con.close();
                CargarTabla();
            }else{
                JOptionPane.showMessageDialog(null, "EL USUARIO QUE INTENTA ELIMINAR NO EXISTE");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
    }//GEN-LAST:event_btnGestionUsuarioEliminarActionPerformed

    private void tblGestionUsuarioTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGestionUsuarioTablaMouseClicked

        try {

            int fila = tblGestionUsuarioTabla.getSelectedRow();

            String usuario = String.valueOf(tblGestionUsuarioTabla.getValueAt(fila, 0));

            this.user = usuario;

            PreparedStatement prepararConsulta;
            ResultSet resultado;

            Connection con = Conexion.getConnection();
            prepararConsulta = con.prepareStatement("SELECT * FROM Usuarios WHERE usuario = ?");
            prepararConsulta.setString(1, usuario);
            resultado = prepararConsulta.executeQuery();

            while (resultado.next()) {
                txtGestionUsuarioUser.setText(resultado.getString("usuario"));
                txtGestionUsuarioNombre.setText(resultado.getString("nombre"));
                txtGestionUsuarioApellido.setText(resultado.getString("apellido"));
                txtGestionUsuarioNumeroCell.setText(resultado.getString("numeroCell"));
                txtGestionUsuarioEmail1.setText(resultado.getString("email"));

            }

            con.commit();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_tblGestionUsuarioTablaMouseClicked

    private void CargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblGestionUsuarioTabla.getModel();

        modeloTabla.setRowCount(0);

        PreparedStatement prepararConsulta;
        ResultSet resultado;

        ResultSetMetaData resultadoMetadata;

        int columnas;

        try {

            Connection con = Conexion.getConnection();
            prepararConsulta = con.prepareStatement("SELECT * FROM Usuarios");
            resultado = prepararConsulta.executeQuery();

            resultadoMetadata = resultado.getMetaData();

            columnas = resultadoMetadata.getColumnCount();

            while (resultado.next()) {

                Object[] filas = new Object[columnas];

                for (int i = 0; i < columnas; i++) {

                    filas[i] = resultado.getObject(i + 1);
                }

                modeloTabla.addRow(filas);
            }

            con.commit();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaGestionDeUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionUsuarioEliminar;
    private javax.swing.JButton btnGestionUsuarioGuardar;
    private javax.swing.JButton btnGestionUsuarioModificar;
    private javax.swing.JButton btnGestionUsuarioRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGestionUsuarioTitulo;
    private javax.swing.JPasswordField passGestionUsuarioPass1;
    private javax.swing.JPasswordField passGestionUsuarioPass2;
    private javax.swing.JTable tblGestionUsuarioTabla;
    private javax.swing.JTextField txtGestionUsuarioApellido;
    private javax.swing.JTextField txtGestionUsuarioEmail1;
    private javax.swing.JTextField txtGestionUsuarioNombre;
    private javax.swing.JTextField txtGestionUsuarioNumeroCell;
    private javax.swing.JTextField txtGestionUsuarioUser;
    // End of variables declaration//GEN-END:variables
}
