/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallaLogin;

import conectarse.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import pantallaRegistrarse.PantallaRegistrarse;
import pntallaPrincipal.PantallaPrincipal;

/**
 *
 * @author Napster
 */
public class PantallaLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PantallaLogin() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbLoginTitulo = new javax.swing.JLabel();
        txtLoginUser = new javax.swing.JTextField();
        pasLoginPassword = new javax.swing.JPasswordField();
        btnLoginIngresar = new javax.swing.JButton();
        btnLoginResistrarse = new javax.swing.JButton();
        lbLoginPassword = new javax.swing.JLabel();
        lbLoginUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLoginTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbLoginTitulo.setText("LOGIN USER");
        jPanel1.add(lbLoginTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, 51));
        jPanel1.add(txtLoginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 410, 40));

        pasLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasLoginPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(pasLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 410, 40));

        btnLoginIngresar.setText("INGRESAR");
        btnLoginIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, 60));

        btnLoginResistrarse.setText("REGISTRARSE");
        btnLoginResistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginResistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginResistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 180, 60));

        lbLoginPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLoginPassword.setText("PASSWORD");
        jPanel1.add(lbLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 40));

        lbLoginUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLoginUsuario.setText("USUARIO");
        jPanel1.add(lbLoginUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pasLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasLoginPasswordActionPerformed

    private void btnLoginIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginIngresarActionPerformed
        
        String nombreUsuario = txtLoginUser.getText();
        String clave = String.valueOf(pasLoginPassword.getPassword());

        PreparedStatement prepararConsulta;
        ResultSet resultado;

        if (nombreUsuario.length() == 0 && clave.length() == 0) {
            JOptionPane.showMessageDialog(null, "DIGITE SU USUARIO Y SU PASSWORD");

        } else if (nombreUsuario.length() == 0) {
            JOptionPane.showMessageDialog(null, "DIGITE SU USUARIO");

        } else if (clave.length() == 0) {
            JOptionPane.showMessageDialog(null, "DIGITE SU PASSWORD");

        } else {
            
            try {
                
                Connection conn;
                conn = Conexion.getConnection();
                
                prepararConsulta = conn.prepareStatement("SELECT * FROM usuarios WHERE usuario = ? and passwordUser = ?");
                prepararConsulta.setString(1, nombreUsuario);
                prepararConsulta.setString(2, clave);

                resultado = prepararConsulta.executeQuery();

                if (resultado.next()) {
                    JOptionPane.showMessageDialog(null, "Bienvenido " + nombreUsuario.toUpperCase());
                    PantallaPrincipal formularioPrincipal = new PantallaPrincipal();
                    formularioPrincipal.setVisible(true);
                    this.setVisible(false);
                } else {
                    //Si el usuario no esta registrado mandara este mensaje
                    JOptionPane.showMessageDialog(null, "Usuario no Registrado \n Usuario y Password Invalidos no Coinciden");

                }
                //luego ceeramos la coneccion 
                conn.close();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }

        }

    }//GEN-LAST:event_btnLoginIngresarActionPerformed

    private void btnLoginResistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginResistrarseActionPerformed
       PantallaRegistrarse formularioRegistrarse = new PantallaRegistrarse();
       formularioRegistrarse.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnLoginResistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginIngresar;
    private javax.swing.JButton btnLoginResistrarse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbLoginPassword;
    private javax.swing.JLabel lbLoginTitulo;
    private javax.swing.JLabel lbLoginUsuario;
    private javax.swing.JPasswordField pasLoginPassword;
    private javax.swing.JTextField txtLoginUser;
    // End of variables declaration//GEN-END:variables
}
