
package pntallaPrincipal;

import pantallaGestionUsuarios.PantallaGestionDeUsuario;
import pantallaGestionProductos.PantallaGestionDeProductos;
import pantallaLogin.PantallaLogin;

public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrincipalUsuarios = new javax.swing.JButton();
        btnPrincipalProductos = new javax.swing.JButton();
        lbPrincipalTitulo = new javax.swing.JLabel();
        lbPrincipalUsiarios = new javax.swing.JLabel();
        lbPrincipalProductos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipalUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/logoUSER.png"))); // NOI18N
        btnPrincipalUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrincipalUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, 190));

        btnPrincipalProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/logoUsuarios.png"))); // NOI18N
        btnPrincipalProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrincipalProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 190, 190));

        lbPrincipalTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbPrincipalTitulo.setText("PANTALLA PRICIPAL");
        jPanel1.add(lbPrincipalTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 390, 60));

        lbPrincipalUsiarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbPrincipalUsiarios.setText("USUARIOS");
        jPanel1.add(lbPrincipalUsiarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 100, 30));

        lbPrincipalProductos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbPrincipalProductos.setText("PRODUCTOS");
        jPanel1.add(lbPrincipalProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 120, 30));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipalUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalUsuariosActionPerformed
        PantallaGestionDeUsuario formularioGestionDeUsuario = new PantallaGestionDeUsuario();
        formularioGestionDeUsuario.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnPrincipalUsuariosActionPerformed

    private void btnPrincipalProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalProductosActionPerformed
        PantallaGestionDeProductos formularioGestionDeProductos = new PantallaGestionDeProductos();
        formularioGestionDeProductos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPrincipalProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PantallaLogin formularioLogin = new PantallaLogin();
        formularioLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrincipalProductos;
    private javax.swing.JButton btnPrincipalUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPrincipalProductos;
    private javax.swing.JLabel lbPrincipalTitulo;
    private javax.swing.JLabel lbPrincipalUsiarios;
    // End of variables declaration//GEN-END:variables
}
